title: 'nindevdo'
description: "An Org"
url: "https://nindevdo.com"

header_pages:
  - index.md
#  - about.md
#  - contact.md

style: hacker

footer: 'Support us with bitcoin <img src = "assets/bitcoin-coinbase.png" alt="bitcoin" border = "0"/>'

google_analytics:

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console