title: 'nindevdo'
description: "An Org"
#baseurl: "/jekyll-theme-console-demo-hacker"
url: "https://nindevdo.com"

header_pages:
  - index.md
  - about.md
  - contact.md

style: hacker

footer: 'Support us with <a href="#">bitcoin</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console